name: Generate Report Action
run-name: ${{ github.actor }} is generating a new report.
on: [push]
jobs:
  Generate-Report:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Weights & Biases Report
      uses: andrewtruong/wandb_create_report_action@v0.04
      with:
        wandb_api_key: ${{ secrets.wandb_api_key }}
        report_template_filename: template.py