name: Generate Report
run-name: ${{ github.actor }} is starting a launch agent
on: [push]
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - name: Launch W&B Agent
      uses: andrewtruong/wandb_create_report_action@v0.05
      with:
        wandb_api_key: ${{ secrets.wandb_api_key }}
        entity: megatruong
        queue: example-local-process