name: Start Launch Agent
run-name: ${{ github.actor }} is starting a launch agent
on:
  workflow_dispatch:
    inputs:
      entity:
        required: true
      queue:
        required: true
jobs:
  run-launch-agent:
    runs-on: ubuntu-latest
    container: ubuntu
    timeout-minutes: 2  # better to add no-activity counter on agent?
    steps:
    - name: Launch W&B Agent
      uses: andrewtruong/wandb-launch-agent@master
      with:
        wandb_api_key: ${{ secrets.wandb_api_key }}
        entity: ${{ inputs.entity }}
        queue: ${{ inputs.queue }}
    env:
      WANDB_BASE_URL: ${{ secrets.wandb_base_url }}
